apiVersion: v1
kind: ServiceAccount
metadata:
  name: console
  namespace: dashboard
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: console-secret
  namespace: dashboard
  annotations:
    kubernetes.io/service-account.name: console